baseurl = "https://example.com"
languageCode = "en"
title = "Hugo Kiss theme"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/ribice\">Emir Ribic</a> 2017"
disqusShortname = "shortname"
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true


[params.assets]
customCSS = ["css/custom.css"]

[params.info]
goatcounter = "" # Goatcounter code, it's the subdomain part (https://{code}.goatcounter.com/count)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
enableUtterances = true # Adds utterances comments to posts

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "ribicemir"
github = "ribice"
email = "ribice@gmail.com"
linkedin = "ribice"
facebook = "ribice"
instagram = ""
codepen = ""

[params.utterances]

repo = "dcefram/blog"   # github repo path
issueTerm = "pathname"  # valid values: pathname, url, title, og:title, <issue-term>,
label = ""
theme = "github-light"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true